const menu = [
  {
    id: 1,
    name: "Spaghetti Bolognese",
    price: "159 kr",
    ingredients: "Spaghetti, kjøttsaus, parmesan",
    category: "Hovedrett",
  },
  {
    id: 2,
    name: "Kremet Kyllingsuppe",
    price: "129 kr",
    ingredients: "Kylling, fløte, gulrøtter, selleri",
    category: "Forrett",
  },
  {
    id: 3,
    name: "Margarita Pizza",
    price: "169 kr",
    ingredients: "Tomatsaus, mozzarella, basilikum",
    category: "Hovedrett",
  },
  {
    id: 4,
    name: "Sushi Mix",
    price: "229 kr",
    ingredients: "Laks, tunfisk, reker, ris",
    category: "Hovedrett",
  },
  {
    id: 5,
    name: "Cæsarsalat",
    price: "139 kr",
    ingredients: "Romanosalat, kylling, parmesan, dressing",
    category: "Forrett",
  },
  {
    id: 6,
    name: "Brownie med Is",
    price: "89 kr",
    ingredients: "Brownie, vaniljeis, sjokoladesaus",
    category: "Dessert",
  },
  {
    id: 7,
    name: "Taco Tallerken",
    price: "199 kr",
    ingredients: "Kjøttdeig, mais, ost, guacamole",
    category: "Hovedrett",
  },
  {
    id: 8,
    name: "Pannekaker med Syltetøy",
    price: "99 kr",
    ingredients: "Pannekaker, jordbærsyltetøy, sukker",
    category: "Dessert",
  },
  {
    id: 9,
    name: "Reker med Sitron",
    price: "149 kr",
    ingredients: "Reker, sitron, dill, brød",
    category: "Forrett",
  },
  {
    id: 10,
    name: "Entrecôte med Grønnsaker",
    price: "289 kr",
    ingredients: "Entrecôte, asparges, poteter, peppersaus",
    category: "Hovedrett",
  },
];
export default menu;
